name: Set Version

on:
  workflow_call:
    inputs:
      force-bump:
        type: string
        description: "Force version bump type (major, minor, patch)"
        required: false
      runner:
        type: string
        description: "GitHub runner to use"
        default: "ubuntu-dagger"
        required: false

jobs:
  set-version:
    runs-on: ubuntu-dagger

    steps:
      - name: Checkout repository
        uses: actions/checkout@v6
        with:
          fetch-depth: 0

      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.9.1
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Set Version
        run: |
          dagger call git-repo \
           --ssh=${SSH_AUTH_SOCK} \
            tag-and-push \
            --force-bump=${{ inputs.force-bump }}
