name: Infra Deploy

on:
  workflow_call:

jobs:
  deploy:
    name: Infra Deploy
    runs-on: ubuntu-dagger
    steps:
      - name: Checkout infrastructure config
        uses: actions/checkout@v6

      - name: Deploy with helmfile
        env:
          CHARTMUSEUM_USER: ${{ secrets.ORG_CHARTMUSEUM_USER }}
          CHARTMUSEUM_PASS: ${{ secrets.ORG_CHARTMUSEUM_PASS }}
        run: |
          helmfile apply --suppress-secrets
